version: '3'
services:
  bench:
    build:
      context: bench
    links:
      - mysql
    args:
      - target_branch
  nginx:
    build: nginx
    links:
      - webapp
    ports:
      - "80:80"
  webapp:
    #image: matsuu/isucon4-qualifier-webapp-go:latest
    build:
      context: webapp/go
      args:
        - build_branch
    links:
      - mysql
      - redis
    ports:
      - "8080"
      - "6060"
    environment:
      ISU4_DB_USER: isucon
      ISU4_DB_PASSWORD: isucon
      ISU4_DB_HOST: mysql
      ISU4_DB_PORT: 3306
  mysql:
    image: mysql:5.5
    ports:
      - "3306"
    command: ["--max_allowed_packet=300M"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    build: redis
    ports:
    - "6379"
